# Generated by Django 3.2.5 on 2022-07-19 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HouseTrack', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='house',
            name='renters',
        ),
        migrations.RemoveField(
            model_name='utility',
            name='user',
        ),
    ]
