# Generated by Django 3.2.5 on 2022-07-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseTrack', '0004_auto_20220719_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='morgage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='home',
            name='rent',
            field=models.IntegerField(default=0),
        ),
    ]
