# Generated by Django 3.2.5 on 2022-07-19 20:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HouseTrack', '0006_auto_20220719_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='owners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='home',
            name='renters',
            field=models.ManyToManyField(blank=True, related_name='renters', to=settings.AUTH_USER_MODEL),
        ),
    ]
