# Generated by Django 3.2.5 on 2022-07-13 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer', models.CharField(default='', max_length=50)),
                ('payDate', models.DateTimeField()),
                ('payAmount', models.IntegerField(default=0)),
                ('fromAccount', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('rentOffset', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='utility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='', max_length=50)),
                ('payDate', models.DateTimeField()),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ledger')),
                ('payBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.resident')),
            ],
        ),
        migrations.CreateModel(
            name='house',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='House Name', max_length=50)),
                ('address', models.CharField(default='', max_length=50)),
                ('residents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.resident')),
                ('utilities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.utility')),
            ],
        ),
    ]
