# Generated by Django 3.2.5 on 2022-07-15 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='renters',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='renters', to='api.userprofile'),
            preserve_default=False,
        ),
    ]
