# Generated by Django 3.2.5 on 2022-07-14 03:32

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220713_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(default=api.models.gen_unique_code, max_length=6)),
                ('name', models.CharField(default='', max_length=50)),
                ('rentOffset', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='house',
            name='code',
        ),
        migrations.RemoveField(
            model_name='house',
            name='name',
        ),
        migrations.AlterField(
            model_name='house',
            name='residents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AlterField(
            model_name='utility',
            name='payBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.DeleteModel(
            name='resident',
        ),
    ]
