# Generated by Django 3.2.5 on 2022-07-15 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_house_renters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='houses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.house'),
        ),
    ]
