# Generated by Django 3.2.5 on 2022-07-15 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_userprofile_houses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='houses',
        ),
    ]
